services:
  api:
    build:
      context: ./backend-shopping-cart
      dockerfile: Dockerfile
    container_name: shopping_cart_api
    image: shopping_cart_api_image
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
